/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AkadminRouteImport } from './routes/Akadmin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AkadminAbout_mgrRouteImport } from './routes/Akadmin.about_mgr'
import { Route as AkadminCalendarRouteImport } from './routes/Akadmin.calendar'
import { Route as AkadminClientsRouteImport } from './routes/Akadmin.clients'
import { Route as AkadminContentRouteImport } from './routes/Akadmin.content'
import { Route as AkadminFaq_mgrRouteImport } from './routes/Akadmin.faq_mgr'
import { Route as AkadminHeroRouteImport } from './routes/Akadmin.hero'
import { Route as AkadminMarkets_mgrRouteImport } from './routes/Akadmin.markets_mgr'
import { Route as AkadminMessagesRouteImport } from './routes/Akadmin.messages'
import { Route as AkadminNews_mgrRouteImport } from './routes/Akadmin.news_mgr'
import { Route as AkadminNotificationsRouteImport } from './routes/Akadmin.notifications'
import { Route as AkadminOverviewRouteImport } from './routes/Akadmin.overview'
import { Route as AkadminPortfoliosRouteImport } from './routes/Akadmin.portfolios'
import { Route as AkadminPrivacy_policyRouteImport } from './routes/Akadmin.privacy_policy'
import { Route as AkadminReportsRouteImport } from './routes/Akadmin.reports'
import { Route as AkadminSearchRouteImport } from './routes/Akadmin.search'
import { Route as AkadminSecurityRouteImport } from './routes/Akadmin.security'
import { Route as AkadminServices_mgrRouteImport } from './routes/Akadmin.services_mgr'
import { Route as AkadminSettingsRouteImport } from './routes/Akadmin.settings'
import { Route as AkadminSite_designRouteImport } from './routes/Akadmin.site_design'
import { Route as AkadminSub_adminsRouteImport } from './routes/Akadmin.sub_admins'
import { Route as AkadminTasksRouteImport } from './routes/Akadmin.tasks'
import { Route as AkadminTeamRouteImport } from './routes/Akadmin.team'
import { Route as AkadminTestimonialsRouteImport } from './routes/Akadmin.testimonials'
import { Route as AkadminTransactionsRouteImport } from './routes/Akadmin.transactions'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ServiceIdRouteImport } from './routes/service.$id'
import { Route as AkadminClientsClientIdRouteImport } from './routes/Akadmin.clients.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AkadminRoute = AkadminRouteImport.update({
  id: '/Akadmin',
  path: '/Akadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AkadminAbout_mgrRoute = AkadminAbout_mgrRouteImport.update({
  id: '/about_mgr',
  path: '/about_mgr',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminCalendarRoute = AkadminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminClientsRoute = AkadminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminContentRoute = AkadminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminFaq_mgrRoute = AkadminFaq_mgrRouteImport.update({
  id: '/faq_mgr',
  path: '/faq_mgr',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminHeroRoute = AkadminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminMarkets_mgrRoute = AkadminMarkets_mgrRouteImport.update({
  id: '/markets_mgr',
  path: '/markets_mgr',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminMessagesRoute = AkadminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminNews_mgrRoute = AkadminNews_mgrRouteImport.update({
  id: '/news_mgr',
  path: '/news_mgr',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminNotificationsRoute = AkadminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminOverviewRoute = AkadminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminPortfoliosRoute = AkadminPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminPrivacy_policyRoute = AkadminPrivacy_policyRouteImport.update({
  id: '/privacy_policy',
  path: '/privacy_policy',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminReportsRoute = AkadminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminSearchRoute = AkadminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminSecurityRoute = AkadminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminServices_mgrRoute = AkadminServices_mgrRouteImport.update({
  id: '/services_mgr',
  path: '/services_mgr',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminSettingsRoute = AkadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminSite_designRoute = AkadminSite_designRouteImport.update({
  id: '/site_design',
  path: '/site_design',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminSub_adminsRoute = AkadminSub_adminsRouteImport.update({
  id: '/sub_admins',
  path: '/sub_admins',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminTasksRoute = AkadminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminTeamRoute = AkadminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminTestimonialsRoute = AkadminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AkadminRoute,
} as any)
const AkadminTransactionsRoute = AkadminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AkadminRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIdRoute = ServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AkadminClientsClientIdRoute = AkadminClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AkadminClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/Akadmin': typeof AkadminRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/Akadmin/about_mgr': typeof AkadminAbout_mgrRoute
  '/Akadmin/calendar': typeof AkadminCalendarRoute
  '/Akadmin/clients': typeof AkadminClientsRouteWithChildren
  '/Akadmin/content': typeof AkadminContentRoute
  '/Akadmin/faq_mgr': typeof AkadminFaq_mgrRoute
  '/Akadmin/hero': typeof AkadminHeroRoute
  '/Akadmin/markets_mgr': typeof AkadminMarkets_mgrRoute
  '/Akadmin/messages': typeof AkadminMessagesRoute
  '/Akadmin/news_mgr': typeof AkadminNews_mgrRoute
  '/Akadmin/notifications': typeof AkadminNotificationsRoute
  '/Akadmin/overview': typeof AkadminOverviewRoute
  '/Akadmin/portfolios': typeof AkadminPortfoliosRoute
  '/Akadmin/privacy_policy': typeof AkadminPrivacy_policyRoute
  '/Akadmin/reports': typeof AkadminReportsRoute
  '/Akadmin/search': typeof AkadminSearchRoute
  '/Akadmin/security': typeof AkadminSecurityRoute
  '/Akadmin/services_mgr': typeof AkadminServices_mgrRoute
  '/Akadmin/settings': typeof AkadminSettingsRoute
  '/Akadmin/site_design': typeof AkadminSite_designRoute
  '/Akadmin/sub_admins': typeof AkadminSub_adminsRoute
  '/Akadmin/tasks': typeof AkadminTasksRoute
  '/Akadmin/team': typeof AkadminTeamRoute
  '/Akadmin/testimonials': typeof AkadminTestimonialsRoute
  '/Akadmin/transactions': typeof AkadminTransactionsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/service/$id': typeof ServiceIdRoute
  '/Akadmin/clients/$clientId': typeof AkadminClientsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/Akadmin': typeof AkadminRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/Akadmin/about_mgr': typeof AkadminAbout_mgrRoute
  '/Akadmin/calendar': typeof AkadminCalendarRoute
  '/Akadmin/clients': typeof AkadminClientsRouteWithChildren
  '/Akadmin/content': typeof AkadminContentRoute
  '/Akadmin/faq_mgr': typeof AkadminFaq_mgrRoute
  '/Akadmin/hero': typeof AkadminHeroRoute
  '/Akadmin/markets_mgr': typeof AkadminMarkets_mgrRoute
  '/Akadmin/messages': typeof AkadminMessagesRoute
  '/Akadmin/news_mgr': typeof AkadminNews_mgrRoute
  '/Akadmin/notifications': typeof AkadminNotificationsRoute
  '/Akadmin/overview': typeof AkadminOverviewRoute
  '/Akadmin/portfolios': typeof AkadminPortfoliosRoute
  '/Akadmin/privacy_policy': typeof AkadminPrivacy_policyRoute
  '/Akadmin/reports': typeof AkadminReportsRoute
  '/Akadmin/search': typeof AkadminSearchRoute
  '/Akadmin/security': typeof AkadminSecurityRoute
  '/Akadmin/services_mgr': typeof AkadminServices_mgrRoute
  '/Akadmin/settings': typeof AkadminSettingsRoute
  '/Akadmin/site_design': typeof AkadminSite_designRoute
  '/Akadmin/sub_admins': typeof AkadminSub_adminsRoute
  '/Akadmin/tasks': typeof AkadminTasksRoute
  '/Akadmin/team': typeof AkadminTeamRoute
  '/Akadmin/testimonials': typeof AkadminTestimonialsRoute
  '/Akadmin/transactions': typeof AkadminTransactionsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/service/$id': typeof ServiceIdRoute
  '/Akadmin/clients/$clientId': typeof AkadminClientsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/Akadmin': typeof AkadminRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/Akadmin/about_mgr': typeof AkadminAbout_mgrRoute
  '/Akadmin/calendar': typeof AkadminCalendarRoute
  '/Akadmin/clients': typeof AkadminClientsRouteWithChildren
  '/Akadmin/content': typeof AkadminContentRoute
  '/Akadmin/faq_mgr': typeof AkadminFaq_mgrRoute
  '/Akadmin/hero': typeof AkadminHeroRoute
  '/Akadmin/markets_mgr': typeof AkadminMarkets_mgrRoute
  '/Akadmin/messages': typeof AkadminMessagesRoute
  '/Akadmin/news_mgr': typeof AkadminNews_mgrRoute
  '/Akadmin/notifications': typeof AkadminNotificationsRoute
  '/Akadmin/overview': typeof AkadminOverviewRoute
  '/Akadmin/portfolios': typeof AkadminPortfoliosRoute
  '/Akadmin/privacy_policy': typeof AkadminPrivacy_policyRoute
  '/Akadmin/reports': typeof AkadminReportsRoute
  '/Akadmin/search': typeof AkadminSearchRoute
  '/Akadmin/security': typeof AkadminSecurityRoute
  '/Akadmin/services_mgr': typeof AkadminServices_mgrRoute
  '/Akadmin/settings': typeof AkadminSettingsRoute
  '/Akadmin/site_design': typeof AkadminSite_designRoute
  '/Akadmin/sub_admins': typeof AkadminSub_adminsRoute
  '/Akadmin/tasks': typeof AkadminTasksRoute
  '/Akadmin/team': typeof AkadminTeamRoute
  '/Akadmin/testimonials': typeof AkadminTestimonialsRoute
  '/Akadmin/transactions': typeof AkadminTransactionsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/service/$id': typeof ServiceIdRoute
  '/Akadmin/clients/$clientId': typeof AkadminClientsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/Akadmin'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/markets'
    | '/news'
    | '/services'
    | '/Akadmin/about_mgr'
    | '/Akadmin/calendar'
    | '/Akadmin/clients'
    | '/Akadmin/content'
    | '/Akadmin/faq_mgr'
    | '/Akadmin/hero'
    | '/Akadmin/markets_mgr'
    | '/Akadmin/messages'
    | '/Akadmin/news_mgr'
    | '/Akadmin/notifications'
    | '/Akadmin/overview'
    | '/Akadmin/portfolios'
    | '/Akadmin/privacy_policy'
    | '/Akadmin/reports'
    | '/Akadmin/search'
    | '/Akadmin/security'
    | '/Akadmin/services_mgr'
    | '/Akadmin/settings'
    | '/Akadmin/site_design'
    | '/Akadmin/sub_admins'
    | '/Akadmin/tasks'
    | '/Akadmin/team'
    | '/Akadmin/testimonials'
    | '/Akadmin/transactions'
    | '/article/$slug'
    | '/service/$id'
    | '/Akadmin/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/Akadmin'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/markets'
    | '/news'
    | '/services'
    | '/Akadmin/about_mgr'
    | '/Akadmin/calendar'
    | '/Akadmin/clients'
    | '/Akadmin/content'
    | '/Akadmin/faq_mgr'
    | '/Akadmin/hero'
    | '/Akadmin/markets_mgr'
    | '/Akadmin/messages'
    | '/Akadmin/news_mgr'
    | '/Akadmin/notifications'
    | '/Akadmin/overview'
    | '/Akadmin/portfolios'
    | '/Akadmin/privacy_policy'
    | '/Akadmin/reports'
    | '/Akadmin/search'
    | '/Akadmin/security'
    | '/Akadmin/services_mgr'
    | '/Akadmin/settings'
    | '/Akadmin/site_design'
    | '/Akadmin/sub_admins'
    | '/Akadmin/tasks'
    | '/Akadmin/team'
    | '/Akadmin/testimonials'
    | '/Akadmin/transactions'
    | '/article/$slug'
    | '/service/$id'
    | '/Akadmin/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/Akadmin'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/markets'
    | '/news'
    | '/services'
    | '/Akadmin/about_mgr'
    | '/Akadmin/calendar'
    | '/Akadmin/clients'
    | '/Akadmin/content'
    | '/Akadmin/faq_mgr'
    | '/Akadmin/hero'
    | '/Akadmin/markets_mgr'
    | '/Akadmin/messages'
    | '/Akadmin/news_mgr'
    | '/Akadmin/notifications'
    | '/Akadmin/overview'
    | '/Akadmin/portfolios'
    | '/Akadmin/privacy_policy'
    | '/Akadmin/reports'
    | '/Akadmin/search'
    | '/Akadmin/security'
    | '/Akadmin/services_mgr'
    | '/Akadmin/settings'
    | '/Akadmin/site_design'
    | '/Akadmin/sub_admins'
    | '/Akadmin/tasks'
    | '/Akadmin/team'
    | '/Akadmin/testimonials'
    | '/Akadmin/transactions'
    | '/article/$slug'
    | '/service/$id'
    | '/Akadmin/clients/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AkadminRoute: typeof AkadminRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  ServicesRoute: typeof ServicesRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ServiceIdRoute: typeof ServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Akadmin': {
      id: '/Akadmin'
      path: '/Akadmin'
      fullPath: '/Akadmin'
      preLoaderRoute: typeof AkadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Akadmin/about_mgr': {
      id: '/Akadmin/about_mgr'
      path: '/about_mgr'
      fullPath: '/Akadmin/about_mgr'
      preLoaderRoute: typeof AkadminAbout_mgrRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/calendar': {
      id: '/Akadmin/calendar'
      path: '/calendar'
      fullPath: '/Akadmin/calendar'
      preLoaderRoute: typeof AkadminCalendarRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/clients': {
      id: '/Akadmin/clients'
      path: '/clients'
      fullPath: '/Akadmin/clients'
      preLoaderRoute: typeof AkadminClientsRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/content': {
      id: '/Akadmin/content'
      path: '/content'
      fullPath: '/Akadmin/content'
      preLoaderRoute: typeof AkadminContentRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/faq_mgr': {
      id: '/Akadmin/faq_mgr'
      path: '/faq_mgr'
      fullPath: '/Akadmin/faq_mgr'
      preLoaderRoute: typeof AkadminFaq_mgrRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/hero': {
      id: '/Akadmin/hero'
      path: '/hero'
      fullPath: '/Akadmin/hero'
      preLoaderRoute: typeof AkadminHeroRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/markets_mgr': {
      id: '/Akadmin/markets_mgr'
      path: '/markets_mgr'
      fullPath: '/Akadmin/markets_mgr'
      preLoaderRoute: typeof AkadminMarkets_mgrRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/messages': {
      id: '/Akadmin/messages'
      path: '/messages'
      fullPath: '/Akadmin/messages'
      preLoaderRoute: typeof AkadminMessagesRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/news_mgr': {
      id: '/Akadmin/news_mgr'
      path: '/news_mgr'
      fullPath: '/Akadmin/news_mgr'
      preLoaderRoute: typeof AkadminNews_mgrRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/notifications': {
      id: '/Akadmin/notifications'
      path: '/notifications'
      fullPath: '/Akadmin/notifications'
      preLoaderRoute: typeof AkadminNotificationsRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/overview': {
      id: '/Akadmin/overview'
      path: '/overview'
      fullPath: '/Akadmin/overview'
      preLoaderRoute: typeof AkadminOverviewRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/portfolios': {
      id: '/Akadmin/portfolios'
      path: '/portfolios'
      fullPath: '/Akadmin/portfolios'
      preLoaderRoute: typeof AkadminPortfoliosRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/privacy_policy': {
      id: '/Akadmin/privacy_policy'
      path: '/privacy_policy'
      fullPath: '/Akadmin/privacy_policy'
      preLoaderRoute: typeof AkadminPrivacy_policyRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/reports': {
      id: '/Akadmin/reports'
      path: '/reports'
      fullPath: '/Akadmin/reports'
      preLoaderRoute: typeof AkadminReportsRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/search': {
      id: '/Akadmin/search'
      path: '/search'
      fullPath: '/Akadmin/search'
      preLoaderRoute: typeof AkadminSearchRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/security': {
      id: '/Akadmin/security'
      path: '/security'
      fullPath: '/Akadmin/security'
      preLoaderRoute: typeof AkadminSecurityRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/services_mgr': {
      id: '/Akadmin/services_mgr'
      path: '/services_mgr'
      fullPath: '/Akadmin/services_mgr'
      preLoaderRoute: typeof AkadminServices_mgrRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/settings': {
      id: '/Akadmin/settings'
      path: '/settings'
      fullPath: '/Akadmin/settings'
      preLoaderRoute: typeof AkadminSettingsRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/site_design': {
      id: '/Akadmin/site_design'
      path: '/site_design'
      fullPath: '/Akadmin/site_design'
      preLoaderRoute: typeof AkadminSite_designRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/sub_admins': {
      id: '/Akadmin/sub_admins'
      path: '/sub_admins'
      fullPath: '/Akadmin/sub_admins'
      preLoaderRoute: typeof AkadminSub_adminsRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/tasks': {
      id: '/Akadmin/tasks'
      path: '/tasks'
      fullPath: '/Akadmin/tasks'
      preLoaderRoute: typeof AkadminTasksRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/team': {
      id: '/Akadmin/team'
      path: '/team'
      fullPath: '/Akadmin/team'
      preLoaderRoute: typeof AkadminTeamRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/testimonials': {
      id: '/Akadmin/testimonials'
      path: '/testimonials'
      fullPath: '/Akadmin/testimonials'
      preLoaderRoute: typeof AkadminTestimonialsRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/Akadmin/transactions': {
      id: '/Akadmin/transactions'
      path: '/transactions'
      fullPath: '/Akadmin/transactions'
      preLoaderRoute: typeof AkadminTransactionsRouteImport
      parentRoute: typeof AkadminRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$id': {
      id: '/service/$id'
      path: '/service/$id'
      fullPath: '/service/$id'
      preLoaderRoute: typeof ServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Akadmin/clients/$clientId': {
      id: '/Akadmin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/Akadmin/clients/$clientId'
      preLoaderRoute: typeof AkadminClientsClientIdRouteImport
      parentRoute: typeof AkadminClientsRoute
    }
  }
}

interface AkadminClientsRouteChildren {
  AkadminClientsClientIdRoute: typeof AkadminClientsClientIdRoute
}

const AkadminClientsRouteChildren: AkadminClientsRouteChildren = {
  AkadminClientsClientIdRoute: AkadminClientsClientIdRoute,
}

const AkadminClientsRouteWithChildren = AkadminClientsRoute._addFileChildren(
  AkadminClientsRouteChildren,
)

interface AkadminRouteChildren {
  AkadminAbout_mgrRoute: typeof AkadminAbout_mgrRoute
  AkadminCalendarRoute: typeof AkadminCalendarRoute
  AkadminClientsRoute: typeof AkadminClientsRouteWithChildren
  AkadminContentRoute: typeof AkadminContentRoute
  AkadminFaq_mgrRoute: typeof AkadminFaq_mgrRoute
  AkadminHeroRoute: typeof AkadminHeroRoute
  AkadminMarkets_mgrRoute: typeof AkadminMarkets_mgrRoute
  AkadminMessagesRoute: typeof AkadminMessagesRoute
  AkadminNews_mgrRoute: typeof AkadminNews_mgrRoute
  AkadminNotificationsRoute: typeof AkadminNotificationsRoute
  AkadminOverviewRoute: typeof AkadminOverviewRoute
  AkadminPortfoliosRoute: typeof AkadminPortfoliosRoute
  AkadminPrivacy_policyRoute: typeof AkadminPrivacy_policyRoute
  AkadminReportsRoute: typeof AkadminReportsRoute
  AkadminSearchRoute: typeof AkadminSearchRoute
  AkadminSecurityRoute: typeof AkadminSecurityRoute
  AkadminServices_mgrRoute: typeof AkadminServices_mgrRoute
  AkadminSettingsRoute: typeof AkadminSettingsRoute
  AkadminSite_designRoute: typeof AkadminSite_designRoute
  AkadminSub_adminsRoute: typeof AkadminSub_adminsRoute
  AkadminTasksRoute: typeof AkadminTasksRoute
  AkadminTeamRoute: typeof AkadminTeamRoute
  AkadminTestimonialsRoute: typeof AkadminTestimonialsRoute
  AkadminTransactionsRoute: typeof AkadminTransactionsRoute
}

const AkadminRouteChildren: AkadminRouteChildren = {
  AkadminAbout_mgrRoute: AkadminAbout_mgrRoute,
  AkadminCalendarRoute: AkadminCalendarRoute,
  AkadminClientsRoute: AkadminClientsRouteWithChildren,
  AkadminContentRoute: AkadminContentRoute,
  AkadminFaq_mgrRoute: AkadminFaq_mgrRoute,
  AkadminHeroRoute: AkadminHeroRoute,
  AkadminMarkets_mgrRoute: AkadminMarkets_mgrRoute,
  AkadminMessagesRoute: AkadminMessagesRoute,
  AkadminNews_mgrRoute: AkadminNews_mgrRoute,
  AkadminNotificationsRoute: AkadminNotificationsRoute,
  AkadminOverviewRoute: AkadminOverviewRoute,
  AkadminPortfoliosRoute: AkadminPortfoliosRoute,
  AkadminPrivacy_policyRoute: AkadminPrivacy_policyRoute,
  AkadminReportsRoute: AkadminReportsRoute,
  AkadminSearchRoute: AkadminSearchRoute,
  AkadminSecurityRoute: AkadminSecurityRoute,
  AkadminServices_mgrRoute: AkadminServices_mgrRoute,
  AkadminSettingsRoute: AkadminSettingsRoute,
  AkadminSite_designRoute: AkadminSite_designRoute,
  AkadminSub_adminsRoute: AkadminSub_adminsRoute,
  AkadminTasksRoute: AkadminTasksRoute,
  AkadminTeamRoute: AkadminTeamRoute,
  AkadminTestimonialsRoute: AkadminTestimonialsRoute,
  AkadminTransactionsRoute: AkadminTransactionsRoute,
}

const AkadminRouteWithChildren =
  AkadminRoute._addFileChildren(AkadminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AkadminRoute: AkadminRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  ServicesRoute: ServicesRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ServiceIdRoute: ServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
